import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
const ethers = require("ethers");


export default function Home() {
  const [Address, setAddress] = useState('');
  const [balance, setbalance] = useState();
  const [iscontract, setiscontract] = useState(null);
  const [nonce, setnonce] = useState(null);
  const [blocknumber, setblocknumber] = useState(null);
  console.log("iscontract", iscontract);
  const providers = new ethers.providers.JsonRpcProvider("https://ropsten.infura.io/v3/d21c9a0af06049d980fc5df2d149e4bb");
  console.log("providers", providers);
  const getTx = async (address) => {
    const length = await providers.getCode(address);
    console.log("length", length);
    if (length.length > 0) {
      setiscontract(true);
    }
    console.log(iscontract);
    const bal = await providers.getBalance(address);
    setbalance(ethers.BigNumber.from(bal).toString());

    const non = await providers.getTransactionCount(address);
    setnonce(non);
    const blocknum = await providers.getBlockNumber();
    setblocknumber(blocknum);



  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ropsten Block Explorer
        </h1>

        <div className={styles.grid}>
          <input
            placeholder="Enter address"
            onChange={(e) => setAddress(e.target.value)}
          />
          <div>

            <button
              onClick={() => {
                getTx(Address);


              }}

            >
              Click
            </button>
          </div>


        </div>
        <div>
          <h2>Balance: {(balance / 10 ** 18).toFixed(2)}  ETH</h2 >
          {<h2>Contract : {iscontract != null ? iscontract : ""}</h2>}
          <h2>Nonce: {nonce}</h2>
          <h2>BlockNumber: {blocknumber}</h2>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
